site_name: My Docs
site_url: https://temeriamos.github.com/holamundo-pyside6.git
docs_dir: 'docs_src'
site_dir: 'docs'
nav:
  - Inicio: README.md
  - About: About.md
  - Manual de usuario: Manual_De_Usuario.md
  - Manual de Referencia: Manual_De_Referencia.md
  - Guía de instalación: Manual_De_Instalacion.md
  - PDF: PDF.md
theme: material
plugins:
  - search
  - pdf-export
  - with-pdf:
      author: 'Temeriamos'
      copyright: '2022'
      cover: true
      back_cover: true
      cover_title: 'My Docs'
      cover_subtitle: 'Manual de usuario'
      toc_title: 'Contenido'
      toc_levels: 2
      ordered_chapters_level: 2
      output_path: pdf/documentacionCompleta.pdf